version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ignite_timer
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres